name: Run Python Tests
on:
  push:
    branches:
      - master
  
jobs:
  pytest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Python 3
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Check my secret
        run: echo aa ${{secrets.PSJ_TEST_TOKEN}}
      - name: Check environment variable
        run: echo repo $GITHUB_REPOSITORY $GITHUB_HEAD_REF
      - name: Run tests with pytest
        run: PYTHONPATH=src pytest 
  black:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Python 3
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Install Black
        run: pip install black
      - name: Run black --check .
        run: black --check .
      - name: If needed, commit black changes
        if: failure()
        run: |
          black .
          git config --global user.name 'autoblack'
          git config --global user.email 'perstofferjensen@gmail.com'
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY
          git checkout $GITHUB_HEAD_REF
          git commit -am "fixup: Format Python code with Black"
          git push
